name: PHP Setup
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: installs php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Take git pull
      run: ~/deploy.sh
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
  
