name: PHP Setup
on: [push]
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Deploy to Staging server
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.SERVER_SSH_KEY }}
    - name: rsync over ssh
      run: |
        rsync -a  -e "ssh -o StrictHostKeyChecking=no" ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/ubuntu/deploy.sh
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "./deplo.sh"
  
