name: PHP Setup
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Key
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
    - name: Take git pull
      run: /home/ubuntu/deploy.sh
  
